<div class="navbar-wrapper">
 
      <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="./Default.aspx">Jopix's Zore</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><a href="#blog">博文</a></li>
                <li><a href="#photo">相册</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">other <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">留言</a></li>
                    <li><a href="#">关于 Jopix</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
                <ul class="nav" style="float:right">
                    <li><a href="page/SingUp.aspx">登录</a></li>
                </ul>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
    </div>